### PR TITLE
Fix #132

### LINKED ISSUE #132: reflectable fails with prefixed annotations
```dart
import 'package:dryice/dryice.dart' as di;

@di.injectable
class MaterialApplication {
    void run() {}
}
```
What reflectable builder generates:
```dart
import "dart:core";
import 'dart:async' as prefix10;
import 'dart:html' as prefix9;
import 'package:dryice/dryice.dart' as prefix0;
...

       new r.NonGenericClassMirrorImpl(
            r"MaterialApplication",
            r"mdlcore.MaterialApplication",
            7,
            1,
            const prefix0.InjectAnnotation(),
            const <int>[20, 21],
            const <int>[15, 16, 17, 18, 19, 20],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix2.MaterialApplication() : null},
            1,
            1,
            const <int>[],
            const <Object>[prefix0.di.injectable],
            null),
```
This is where the problem occures: `const <Object>[prefix0.di.injectable],`
double prefix...

### PR DESCRIPTION
**Pull request by eernstg**
Reflectable code generation is now stripping client import prefix when generating metadata code for a const variable. For instance, before this PR we generated `prefix2.di.inject`, where `di.inject` is the term used in a client library to access the top level declaration `inject` and `di` is an import prefix, and now we generate something like `prefix2.inject`.

### CODE REVIEW

File: lib/src/builder_implementation.dart [hunk 1]
```diff
@@ -4534,13 +4513,43 @@ String _extractMetadataCode(Element element, Resolver resolver,
...
 
   return _formatAsConstList("Object", metadataParts);
 }
 
+/// Extract the plain name from by [identifier] by stripping off the
+/// library import prefix at front, if any.
+String _extractNameWithoutPrefix(Identifier identifier, Element errorTarget) {
+  String name;
+  if (identifier is SimpleIdentifier) {
+    name = "$identifier";
```
Comment (sigurdm) [inline lib/src/builder_implementation.dart]: I worry about using `toString()` it is usually mostly a debugging tool. Is there not a `Identifier.token` or similar getter you could use returning a string? (Not that it is different from the existing code).

File: lib/src/builder_implementation.dart [hunk 2]
```diff
@@ -4534,13 +4513,43 @@ String _extractMetadataCode(Element element, Resolver resolver,
       if (_isPrivateName(annotationNode.name.name)) {
         _severe("Cannot access private name ${annotationNode.name}", element);
       }
-      metadataParts.add("$prefix${annotationNode.name}");
+      String name = _extractNameWithoutPrefix(annotationNode.name, element);
+      if (_isPrivateName(name)) {
+        _severe("Cannot access private name $name", element);
```
Comment (sigurdm) [inline lib/src/builder_implementation.dart]: Not specific to this change, but it would be great if we could output a source location of where name is accessed.

File: lib/src/builder_implementation.dart [hunk 3]
```diff
@@ -4534,13 +4513,43 @@ String _extractMetadataCode(Element element, Resolver resolver,
...
+      }
+      metadataParts.add("$prefix$name");
     }
   }
 
   return _formatAsConstList("Object", metadataParts);
 }
 
+/// Extract the plain name from by [identifier] by stripping off the
```
Comment (sigurdm) [inline lib/src/builder_implementation.dart]: Seems you have a "by" too much

File: lib/src/builder_implementation.dart (hunk 2 above)
Comment (eernstg) [reply lib/src/builder_implementation.dart]: This is already in place: We pass `element` as the `errorTarget` which is used to print a source code location, and that gets passed on to `_formatDiagnosticMessage` where the source code location is extracted and included in the returned string.

File: lib/src/builder_implementation.dart (hunk 3 above)
Comment (eernstg) [reply lib/src/builder_implementation.dart]: Indeed, fixed!
